"""Production-v2: isolated nine-engine trading runtime.

E6 is the single authoritative opportunity/setup specialist. Compatibility
membranes may enrich its output, but E9 remains the sole execution authority.
"""

from .pipeline import ProductionPipeline
from . import pipeline as _pipeline_module
from . import e2_brain as _e2_module
from . import e6_brain as _e6_module
from . import e8_brain as _e8_module
from . import e9_brain as _e9_module
from . import e5_brain as _e5_module
from . import market_data as _market_data_module
from . import professional_opportunity as _professional_opportunity_module
from . import opportunity_lifecycle as _opportunity_lifecycle_module
from .bootstrap_surgery import install as _install_bootstrap_surgery
from .e2_runtime_binding import install as _install_e2_opportunity_book
from .e6_runtime_authority import install as _install_e6_runtime_authority
from .e7_thesis_boundary import install as _install_e7_thesis_boundary
from .e8_applicability_boundary import install as _install_e8_applicability_boundary
from .e9_watch_boundary import install as _install_e9_watch_boundary
from .mtf_runtime import install as _install_mtf_runtime
from .final_runtime_binding import install as _install_final_runtime_binding
from .evidence_collaboration_runtime import install as _install_evidence_collaboration
from .e9_thesis_contract import install as _install_e9_thesis_contract
from .runtime_trace_boundary import install as _install_runtime_trace_boundary
from .opportunity_lifecycle_runtime import install as _install_opportunity_lifecycle_runtime
from .professional_opportunity_surgery import install as _install_professional_opportunity
from .terminal_opportunity_runtime import install as _install_terminal_opportunity_runtime
from .opportunity_timing_runtime_hotfix import install as _install_opportunity_timing_hotfix
from .opportunity_lifecycle_timing import install as _install_opportunity_lifecycle_timing
from .opportunity_lifecycle_promotion import install as _install_opportunity_lifecycle_promotion
from .p0_opportunity_integrity import install as _install_p0_opportunity_integrity
from .opportunity_lifecycle_contract_surgery import install as _install_lifecycle_contract_surgery
from .professional_runtime import install as _install_professional_runtime
from .professional_e9_runtime import install as _install_professional_e9_runtime
from .professional_lifecycle_guard import install as _install_professional_lifecycle_guard
from .professional_e5_direct_runtime import install as _install_professional_e5_direct
from .professional_lifecycle_identity_runtime import install as _install_professional_lifecycle_identity
from .professional_lifecycle_authority_runtime import install as _install_professional_lifecycle_authority
from .professional_e5_direct_runtime_v2 import install as _install_professional_e5_direct_v2
from .professional_lifecycle_contract_v2 import install as _install_professional_lifecycle_contract_v2

_install_bootstrap_surgery(_pipeline_module)
_install_mtf_runtime(_pipeline_module, _market_data_module)
_install_e2_opportunity_book(_pipeline_module, _e2_module)
_install_e6_runtime_authority(_e6_module)
_pipeline_module.analyze_e6 = _e6_module.analyze_e6
_pipeline_module._E6_RUNTIME_OVERRIDE = _e6_module.analyze_e6
_install_e8_applicability_boundary(_e8_module)
_pipeline_module.analyze_e8 = _e8_module.analyze_e8
_install_e9_watch_boundary(_e9_module)
_install_e9_thesis_contract(_e9_module)
_pipeline_module.analyze_e9 = _e9_module.analyze_e9
_install_evidence_collaboration(_e6_module, _e9_module)
_install_e7_thesis_boundary(_pipeline_module)
_install_final_runtime_binding(_pipeline_module, _e6_module, _e8_module, _e9_module)
_install_runtime_trace_boundary(_pipeline_module)
_install_opportunity_lifecycle_runtime(_pipeline_module)
_install_terminal_opportunity_runtime(_pipeline_module)
_install_lifecycle_contract_surgery(_opportunity_lifecycle_module, _pipeline_module)
_install_professional_opportunity(_professional_opportunity_module, _pipeline_module)
_install_opportunity_timing_hotfix(_pipeline_module)
_install_opportunity_lifecycle_timing(_pipeline_module)
_install_opportunity_lifecycle_promotion()
_install_p0_opportunity_integrity(_pipeline_module)
_install_professional_runtime(_pipeline_module)
_install_professional_lifecycle_guard(_pipeline_module)
_install_professional_e9_runtime(_pipeline_module)
_install_professional_e5_direct(_e5_module)
_install_professional_lifecycle_identity(_opportunity_lifecycle_module)
_install_professional_lifecycle_authority(_pipeline_module)
_install_professional_e5_direct_v2(_e5_module)
_install_professional_lifecycle_contract_v2(_opportunity_lifecycle_module)

__all__ = ["ProductionPipeline"]
